import { loadFile as lf } from '@toolkip/server';
import { parseFile } from './parseFile';

const ALLOWED_EXTENSION = /\.md$/i;
const DANGEROUS_PROTOCOLS = /^(javascript|data|file|vbscript):/i;
const BLOB_URL = /^blob:/i;
const NULL_BYTE = /\0/;

const validateFilename = (filename: string): void => {
  if (!filename || typeof filename !== 'string') {
    throw new Error('Invalid filename: must be a non-empty string');
  }
  if (NULL_BYTE.test(filename)) {
    throw new Error('Invalid filename: null bytes are not permitted');
  }
  if (DANGEROUS_PROTOCOLS.test(filename.trim())) {
    throw new Error('Invalid filename: protocol not permitted');
  }
  // blob: URLs are generated by URL.createObjectURL() for user-uploaded files;
  // they are origin-scoped and safe, so skip the extension check for them.
  if (BLOB_URL.test(filename.trim())) {
    return;
  }
  if (!ALLOWED_EXTENSION.test(filename)) {
    throw new Error('Invalid filename: only .md files are permitted');
  }
};

export const loadFile = async (filename: string) => {
  validateFilename(filename);
  return await lf({ filename });
};

export const loadAndParseFile = async (filename: string) => {
  validateFilename(filename);
  const loaded = await lf({ filename })
  const parsed = parseFile(loaded)
  return parsed
}