import { loadFile as lf } from '@toolkip/server';
import { parseFile } from './parseFile';

const ALLOWED_EXTENSION = /\.md$/i;
const MAX_FILE_SIZE = 500_000; // ~500KB in characters
const DANGEROUS_PROTOCOLS = /^(javascript|data|file|vbscript):/i;
const BLOB_URL = /^blob:/i;
const NULL_BYTE = /\0/;
const LOOPBACK = /^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])/i;

const validateFilename = (filename: string): void => {
  if (!filename || typeof filename !== 'string') {
    throw new Error('Invalid filename: must be a non-empty string');
  }
  if (NULL_BYTE.test(filename)) {
    throw new Error('Invalid filename: null bytes are not permitted');
  }
  if (DANGEROUS_PROTOCOLS.test(filename.trim())) {
    throw new Error('Invalid filename: protocol not permitted');
  }
  // blob: URLs are generated by URL.createObjectURL() for user-uploaded files;
  // they are origin-scoped and safe, so skip the extension check for them.
  if (BLOB_URL.test(filename.trim())) {
    return;
  }
  if (LOOPBACK.test(filename.trim())) {
    throw new Error('Invalid URL: requests to loopback addresses are not permitted');
  }
  if (!ALLOWED_EXTENSION.test(filename)) {
    throw new Error('Invalid filename: only .md files are permitted');
  }
};

export const loadFile = async (filename: string) => {
  validateFilename(filename);
  const content = await lf({ filename });
  if (content.length > MAX_FILE_SIZE) {
    throw new Error(`File too large: maximum size is ${MAX_FILE_SIZE / 1000}KB`);
  }
  return content;
};

export const loadAndParseFile = async (filename: string) => {
  const loaded = await loadFile(filename);
  const parsed = parseFile(loaded);
  return parsed;
}
